platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

flutter_root = '/usr/local/Caskroom/flutter/3.29.3/flutter'
load File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
